#! /usr/bin/env bash
system_brightness_source="/sys/class/backlight/intel_backlight/brightness"
system_max_brightness=$(cat "/sys/class/backlight/intel_backlight/max_brightness")
# use `xrandr | grep connect` to get list of all avialiable screens with basic info
display=""

# if `display` not defined, the primary screen is used
if [ "$display" == "" ]
then
    display=$(xrandr | grep -m 1 ' primary ' | awk '{print $1}')
fi

# if given an parameter, set the parameter as the brightness
if [ "$1" == "" ]
then
    # monitor change of brightness in system_brightness_source
    inotifywait -m -e CLOSE_WRITE /sys/class/backlight/intel_backlight/brightness | while read CLOSE_WRITE; do
    brightness=$(cat $system_brightness_source)
    xrandr --output $display --brightness $(echo "$brightness/$system_max_brightness*0.95 + 0.05" | bc -l)
    done
else
    xrandr --output $display --brightness $1
fi
